/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Database.CRUD;

/**
 *
 * @author ThinkPad
 */
public class SessionPlanner extends javax.swing.JFrame {

    /**
     * Creates new form SessionPlanner
     */
    public SessionPlanner() {
        initComponents();
    }

    public SessionPlanner(String userName) {
        this();
        jLUserName.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btGrpCheckBoxes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtIDcard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtNameC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtHour = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jtDateS = new com.toedter.calendar.JDateChooser();
        jcCode = new javax.swing.JCheckBox();
        jcParking = new javax.swing.JCheckBox();
        jcDriving = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSession = new javax.swing.JTable();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtIDsession = new javax.swing.JTextField();
        jLUserName = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driving-school.png"))); // NOI18N
        jLabel1.setText("Session Planner");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identity Card Number");

        jtIDcard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtIDcard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtIDcardKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtIDcardKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtIDcardKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Condidate Full Name");

        jtNameC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtNameC.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Session Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hour");

        jtHour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Type");

        jcCode.setBackground(new java.awt.Color(0, 153, 153));
        btGrpCheckBoxes.add(jcCode);
        jcCode.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jcCode.setForeground(new java.awt.Color(255, 255, 255));
        jcCode.setText("Code");

        jcParking.setBackground(new java.awt.Color(0, 153, 153));
        btGrpCheckBoxes.add(jcParking);
        jcParking.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jcParking.setForeground(new java.awt.Color(255, 255, 255));
        jcParking.setText("Parking ");

        jcDriving.setBackground(new java.awt.Color(0, 153, 153));
        btGrpCheckBoxes.add(jcDriving);
        jcDriving.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jcDriving.setForeground(new java.awt.Color(255, 255, 255));
        jcDriving.setText("Driving");
        jcDriving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcDrivingActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 153, 153));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 153, 153));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eraser.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        TableSession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Card", "Full Name ", "SessionID", "Date ", "Hour", "Type"
            }
        ));
        TableSession.setSelectionBackground(new java.awt.Color(255, 50, 91));
        TableSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSessionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSession);

        btnModify.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnModify.setForeground(new java.awt.Color(0, 153, 153));
        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit (1).png"))); // NOI18N
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 153, 153));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(250, 207, 207));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/return.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Session ID");

        jtIDsession.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtIDsessionKeyReleased(evt);
            }
        });

        jLUserName.setBackground(new java.awt.Color(0, 153, 153));
        jLUserName.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(81, 81, 81))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtIDcard)
                                        .addComponent(jtNameC)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jcCode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcParking, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jcDriving, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jtHour, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtDateS, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtIDsession, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModify)
                    .addComponent(btnDelete)
                    .addComponent(jLUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtIDcard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNameC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtIDsession, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtDateS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtHour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcCode)
                            .addComponent(jcParking)
                            .addComponent(jcDriving))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnClear)))
                    .addComponent(jScrollPane1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        jtIDcard.setText("");
        jtNameC.setText("");
        jtDateS.setDateFormatString("");
        jtIDsession.setText("");
        btGrpCheckBoxes.clearSelection();
        jtHour.setValue(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) TableSession.getModel();
        String userName = jLUserName.getText();
        String dbUserName = crud.getUserName(userName);
        try {
            int selectedRow = TableSession.getSelectedRow();
            model.removeRow(selectedRow);
            if (dbUserName.equals(userName)) {
                crud.deleteSession(userName);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No row is selected.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        jtIDcard.setText("");
        jtNameC.setText("");
        jtDateS.setDateFormatString("");
        jtIDsession.setText("");
        btGrpCheckBoxes.clearSelection();
        jtHour.setValue(0);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String IDc = jtIDcard.getText();
        String IDs = jtIDsession.getText();
        String Name = jtNameC.getText();
        String Date = sdf.format(jtDateS.getDate());
        int Hour = (int) jtHour.getValue();
        String Type = "";
        String userName = jLUserName.getText();
        String dbUserName = crud.getUserName(userName);
        if (jcCode.isSelected()) {
            Type = "Code";
        } else if (jcDriving.isSelected()) {
            Type = "Driving";
        } else if (jcParking.isSelected()) {
            Type = "Parking";
        }
        String candidateFullName = crud.getCondidateNameById(IDc);

        if (IDc.isEmpty() || Name.isEmpty() || Date.isEmpty() || Hour == 0 || IDs.isEmpty() || !(jcCode.isSelected() || jcDriving.isSelected() || jcParking.isSelected())) {
            JOptionPane.showMessageDialog(this, "Please enter all fields", "Try again", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) TableSession.getModel();
            model.addRow(new Object[]{IDc, candidateFullName, IDs, Date, Hour, Type});
            jtIDcard.setText("");
            jtNameC.setText("");
            jtIDsession.setText("");
            jtDateS.setCalendar(null);
            btGrpCheckBoxes.clearSelection();
            jtHour.setValue(0);
        }
        jtNameC.setText(crud.getCondidateNameById(IDc));
        if (dbUserName.equals(userName)) {
            if (crud.addSession(IDs, IDc, candidateFullName, Date, Hour, Type, userName)) {
                JOptionPane.showMessageDialog(this, "Session has been added successfully!", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void TableSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSessionMouseClicked
        int selectedRow = TableSession.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableSession.getModel();
        jtIDcard.setText(model.getValueAt(selectedRow, 0).toString());
        jtNameC.setText(model.getValueAt(selectedRow, 1).toString());
        jtIDsession.setText(model.getValueAt(selectedRow, 2).toString());
        Date date;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse(model.getValueAt(selectedRow, 3).toString());
            jtDateS.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        int Hour = Integer.parseInt(String.valueOf(model.getValueAt(selectedRow, 4)));
        jtHour.setValue(Hour);
        String Type = model.getValueAt(selectedRow, 5).toString();
        switch (Type) {
            case "Code":
                jcCode.setSelected(true);
                break;
            case "Driving":
                jcDriving.setSelected(true);
                break;
            case "Parking":
                jcParking.setSelected(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_TableSessionMouseClicked

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        int i = TableSession.getSelectedRow();
        String userName = jLUserName.getText();
        String dbUserName = crud.getUserName(userName);
        DefaultTableModel model = (DefaultTableModel) TableSession.getModel();
        if (i >= 0) {
            String IDc = jtIDcard.getText();
            String Name = jtNameC.getText();
            String IDs = jtIDsession.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String Date = sdf.format(jtDateS.getDate());
            int Hour = (int) jtHour.getValue();
            String candidateFullName = crud.getCondidateNameById(IDc);
            String Type;
            if (jcCode.isSelected()) {
                Type = "Code";
            } else if (jcDriving.isSelected()) {
                Type = "Driving";
            } else if (jcParking.isSelected()) {
                Type = "Parking";
            } else {
                Type = "";
            }
            if (dbUserName.equals(userName)) {
                crud.updateSession(IDs, IDc, candidateFullName, Date, Hour, Type, userName);
                model.setValueAt(IDc, i, 0);
                model.setValueAt(Name, i, 1);
                model.setValueAt(IDs, i, 2);
                model.setValueAt(Date, i, 3);
                model.setValueAt(Hour, i, 4);
                model.setValueAt(Type, i, 5);
                jtNameC.setText(crud.getCondidateNameById(IDc));
            }
            // crud.updateSession(IDs, candidateFullName, IDc, Date, Hour, Type);
            // crud.updateSession(IDs, IDc, candidateFullName, Date, Hour, Type);
        } else {
            JOptionPane.showMessageDialog(this, "No row selected ", "Try again !", JOptionPane.ERROR_MESSAGE);
        }
        jtIDcard.setText("");
        jtNameC.setText("");
        jtDateS.setCalendar(null);
        jtIDsession.setText("");
        btGrpCheckBoxes.clearSelection();
        jtHour.setValue(0);

    }//GEN-LAST:event_btnModifyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        this.toBack();
        home_screen hc = new home_screen();
        hc.setVisible(true);
        hc.toFront();
        // this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtIDcardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIDcardKeyTyped
        // TODO add your handling code here:        
    }//GEN-LAST:event_jtIDcardKeyTyped
    CRUD crud = new CRUD();
    private void jtIDcardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIDcardKeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jtIDcardKeyPressed

    private void jtIDcardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIDcardKeyReleased
        // TODO add your handling code here:
        String idc = jtIDcard.getText().trim();
        jtNameC.setText(crud.getCondidateNameById(idc));
    }//GEN-LAST:event_jtIDcardKeyReleased

    private void jcDrivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcDrivingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcDrivingActionPerformed

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String userName = jLUserName.getText();
        String dbUserName = crud.getUserName(userName);
        if (dbUserName.equals(userName)) {
            crud.displayDataSessionTable(TableSession, userName);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jtIDsessionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIDsessionKeyReleased

    }//GEN-LAST:event_jtIDsessionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SessionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SessionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SessionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SessionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessionPlanner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSession;
    private javax.swing.ButtonGroup btGrpCheckBoxes;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcCode;
    private javax.swing.JCheckBox jcDriving;
    private javax.swing.JCheckBox jcParking;
    private com.toedter.calendar.JDateChooser jtDateS;
    private javax.swing.JSpinner jtHour;
    private javax.swing.JTextField jtIDcard;
    private javax.swing.JTextField jtIDsession;
    private javax.swing.JTextField jtNameC;
    // End of variables declaration//GEN-END:variables
}
